services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  nginx:
    container_name: nginx
    build: ../infra-nginx-dockerized
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:80"

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  helloworld:
    container_name: helloworld
    build: ../helloworld
    env_file:
      - .env
    ports:
      - ${HELLOWORLD_PORT}:${HELLOWORLD_PORT}

  documentation:
    container_name: documentation
    build: ../documentation
    env_file:
      - .env
    ports:
      - "${DOCUMENTATION_PORT}:${DOCUMENTATION_PORT}"

  accounts:
    container_name: accounts
    build: ../accounts
    env_file:
      - .env
    ports:
      - "${ACCOUNTS_PORT}:${ACCOUNTS_PORT}"

volumes:
  portainer_data:
  postgres_data: