services:

  nginx:
    container_name: nginx
    build: ../infra-nginx-dockerized
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - spring_net

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring_net

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - spring_net

  helloworld:
    container_name: helloworld
    build: ../helloworld
    env_file:
      - .env
    ports:
      - "${HELLOWORLD_PORT}:${HELLOWORLD_PORT}"
    networks:
      - spring_net

  documentation:
    container_name: documentation
    build: ../documentation
    env_file:
      - .env
    ports:
      - "${DOCUMENTATION_PORT}:${DOCUMENTATION_PORT}"
    networks:
      - spring_net

#  accounts:
#    container_name: accounts
#    build: ../accounts
#    env_file:
#      - .env
#    depends_on:
#      - postgres
#      - redis
#    ports:
#      - "${ACCOUNTS_PORT}:${ACCOUNTS_PORT}"
#    networks:
#      - spring_net

volumes:
  postgres_data:

networks:
  spring_net:
    driver: bridge